### ISSUE TITLE
Gallery plugin only displays at width of column

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#135]
Some galleries might be smaller than width of column. The current function for sizing gallery doesn't work, perhaps it's overwritten in the stylesheet. 
Maybe it would good to have galleries at "max-width" rather than "width"?

Example: https://magazine.wsu.edu/2016/04/29/close-encounters-from-outer-space/  
<div id="gallery-1" class="gallery galleryid-8594 gallery-columns-1 gallery-size-medium"><div style="padding-bottom: 139.844%;" class="sss">
<figure style="display: block;" class="gallery-item ssslide">

style.css: line 652  
.sss .ssslide {
    width: 100%;
    }

**Comment by philcable** [comment]
This was fixed in #139.
