### ISSUE TITLE
Accessibility, privacy, copyright links in footer

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#145]
To add to the footer:
Copyright © 2017 Board of Regents, Washington State University | [Accessibility ](http://access.wsu.edu/)| [Privacy ](https://policies.wsu.edu/privacy-policy/)| [Copyright](https://ucomm.wsu.edu/wsu-copyright-policy/)

**Comment by jeremyfelt** [comment]
@wsmagazine Should this go below the "WSU HOME | NEWS | etc..." navigation as light text on crimson?
<img width="1018" alt="screen shot 2017-07-15 at 2 01 58 pm" src="https://user-images.githubusercontent.com/286171/28241634-528a1c30-6966-11e7-98ba-b69cf9a807dc.png">

**Comment by philcable** [comment]
Fixed in https://github.com/washingtonstateuniversity/magazine.wsu.edu/pull/152
