### ISSUE TITLE
responsive videos

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/magazine.wsu.edu#41]
find solution for making videos a little more friendly in mobile.
https://stage.magazine.wsu.edu/video/

**Comment by slocker3** [comment]
https://stage.magazine.wsu.edu/video/

**Comment by jeremyfelt** [comment]
We should fix this in https://github.com/washingtonstateuniversity/WSUWP-Plugin-Embeds/issues/30 and then make use of it here.

**Comment by philcable** [comment]
Addressed through https://github.com/washingtonstateuniversity/WSUWP-Plugin-Embeds/pull/33 and https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/pull/316.
