### ISSUE TITLE
Image widths, floats, captions need attention

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/magazine.wsu.edu#53]
Full images need to span 100%. Headshots and other smaller images need to float and allow text to wrap. Captions need to be handled differently on headshots, e.g., https://stage.magazine.wsu.edu/2015/08/16/in-memory-of-erich-joseph-lear-1948-2015/

**Comment by wsmagazine** [comment]
Changes to captions make the galleries dark and not clickable.

**Comment by slocker3** [comment]
Do we want smaller images to wrap?

**Comment by wsmagazine** [comment]
No.

**Comment by slocker3** [comment]
@wsmagazine are we good on this?

**Comment by wsmagazine** [comment]
@slocker3 I think we're good
