### ISSUE TITLE
Social sharing icons need functionality

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/magazine.wsu.edu#7]
Icons appear right below the header and should be on every post page. The icons currently link to WSU channels, they need to go to sharing of the page content on that channel. Not in the attached mockup that there are additional icons, including an email and print.

![web2015prez_frames 020](https://cloud.githubusercontent.com/assets/5604675/9151930/9282e9c6-3dca-11e5-9cee-312a29862f1e.jpg)

**Comment by jeremyfelt** [comment]
Facebook, Twitter, Pinterest, and Google+ are all connected via #42.

**Comment by slocker3** [comment]
Need to add email icon and functionality

**Comment by wsmagazine** [comment]
Could we change email share subject to read "Washington State Magazine" rather than "Magazine Stage Site"?

**Comment by jeremyfelt** [comment]
All set. This inherits automatically from the site's name (Settings -> General), which I just changed. Good catch, because we sometimes miss this before launch. :)
