### ISSUE TITLE
Adjustments to home page magazine banner

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#76]
In mockup, the home page banner is larger. The top navigational icons are also spread out pretty far, so we can get some room for the home page "Washington" banner by compressing that space.

**Comment by slocker3** [comment]
The WSM logo is currently the size that was delivered.

**Comment by wsmagazine** [comment]
Pull icons closer together, then let's take a look at the banner.

**Comment by slocker3** [comment]
I think most of the issue is with the width difference from the mockup to the actual site. The mockup slides that were delivered have the site width at 770px. The site is currently 990px.

Icons have been pulled closer together

**Comment by slocker3** [comment]
@wsmagazine are we happy with the adjustments to the icons and logo proximity?

**Comment by wsmagazine** [comment]
Checking with John P. on this. We're meeting on Monday about web stuff.

**Comment by jeremyfelt** [comment]
Things were looking good at around 125 or 130px high on the WSM logo SVG.
