### ISSUE TITLE
Need to load fonts for the site

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/magazine.wsu.edu#8]
The magazine is using fonts not available in the Spine.

Email from Paxson:

I put the type callouts PDF into the WSMagazine/Redesign/Web/Fonts folder. I cannot give type sizes since I don't know what our overall starting point is for the responsive design.

We own the web fonts for Museo Slab at this point. (We also own for Fertigo Pro/Script & Popvlvs which I use in the print magazine but not yet in the web design.) I have put the webkits for these in the folder.

Here is the info page I sent some time back: http://www.myfonts.com/licensing/webfont/

And the contract page: http://www.myfonts.com/viewlicense.php?lid=1630

I still need to purchase the webkits for Magma II (a better font for web than our plain print Magma), and Stone Humanist. I would like to wait on those until you give me the OK that everything is copacetic with implementation of these webkits on our web server.

**Comment by jeremyfelt** [comment]
Typekit is now enabled (once #10 is deployed shortly). @allenjohns mentioned being able to load these fonts via that.

**Comment by wsmagazine** [comment]
@allenjohns now has the fonts from John Paxson
