### ISSUE TITLE
Gallery fixes on articles

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#80]
Arrows for left/right navigation into the gallery.
Captions below gallery images (no space between captions and images).

**Comment by slocker3** [comment]
Captions moved.

**Comment by slocker3** [comment]
How do we want to treat the arrows if they are over the images? The benefit of having them to the side is so you can always see them.

**Comment by wsmagazine** [comment]
I'll ask John to test inside and out, and different colors.

**Comment by wsmagazine** [comment]
Looks good
