### ISSUE TITLE
As a reader, I want to click something on an issue layout so that I have quick access to the issue's overview

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/magazine.wsu.edu#88]
- [ ] Determine placement of "About this issue"
- [ ] Determine where content for the About This Issue overlay is entered
- [ ] Determine how/where the overlay is displayed

**Comment by wsmagazine** [comment]
Not using this idea for issue landing pages.

**Comment by jeremyfelt** [comment]
Closing due to change in direction.
