### ISSUE TITLE
Provide an interface to organize the issue landing page

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/magazine.wsu.edu#92]
Rather than using the page builder interface and the WSU Home Headlines plugin, we should be able to provide a more focused editing experience for issue landing pages.
- [x] A meta box containing two sections
  - [x] Section 1: Grid of articles in a layout matching the expected issue format
  - [x] Section 2: Articles not yet placed in section 1
- [x] Articles populate with featured image and page headlines information
- [x] Populated information can be overridden on a per article basis for the issue

**Comment by wsmagazine** [comment]
Make sure feature image is used on issue landing pages, including positioning tool.

**Comment by jeremyfelt** [comment]
Closing this out now that 0.10.0 shipped with #132. 🎉
