### ISSUE TITLE
Allow articles without thumbnails to appear on Issue pages

### ISSUE THREAD

**Issue by wsmagazine** [washingtonstateuniversity/magazine.wsu.edu#94]
Currently appears blank if no thumbnail indicated. This is important particularly for older issues of the magazine.

**Comment by jeremyfelt** [comment]
What should be the placeholder or change in display when an article doesn't have a thumbnail?

**Comment by jeremyfelt** [comment]
Deferring to https://github.com/washingtonstateuniversity/magazine.wsu.edu/issues/95#issuecomment-158128463 for the answer to this. :)

**Comment by jeremyfelt** [comment]
Fixed in #97.
