### ISSUE TITLE
Auto populate issue landing pages

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/magazine.wsu.edu#95]
With or without a curated view created via something like #92, old issue landing pages should be automatically generated until manually edited.

**Comment by jeremyfelt** [comment]
When auto generating past issues, we can't always be _automatically_ sure of imagery that allows for a large first section. We should figure out what this looks like. I tossed a quick 65px of margin, but I'm not sure that's the right answer:

![screen shot 2015-11-18 at 5 04 01 pm](https://cloud.githubusercontent.com/assets/286171/11259478/b3cbc638-8e16-11e5-8933-8990118993fc.png)

It may make sense to instead add a grey bar similar to secondary page layouts, see:

![screen shot 2015-11-18 at 5 09 42 pm](https://cloud.githubusercontent.com/assets/286171/11259532/32688594-8e17-11e5-969e-a557a65193b6.png)

@slocker3 @wsmagazine - thoughts?

**Comment by jeremyfelt** [comment]
Here's where we're at with the latest work on #97:

![screen shot 2015-11-18 at 5 36 00 pm](https://cloud.githubusercontent.com/assets/286171/11259935/15327648-8e1b-11e5-8c04-94e6a32699e3.png)

We should figure out:
- Is the grey bar the right answer for automatic issues that have no "feature" item.
- How should articles that have no thumbnails display? This is basically #94 
- I don't think we can guess a subtitle for older articles. Is that ok?

**Comment by wsmagazine** [comment]
I like the gray bar solution for older issues. It fits with the overall look, and we can add feature images for issues on a rolling basis. 
I wonder if we can auto-generate thumbnails from story images? If not, I think we should have the titles span the whole box, since it seems like something is missing if no thumb.
No subtitles are fine with me.

**Comment by jeremyfelt** [comment]
The handling of auto-generated thumbnails could work, though would be pretty involved. Let's plan on not having thumbnails right now and see what we can do to improve that in the future.

Tasks:
- [x] Default gray bar for automatically generated issues.
- [x] Featured images should work as expected when assigned to an automatically generated issue.
- [x] Story titles should span the entire box when a thumbnail is not available.

**Comment by jeremyfelt** [comment]
Rather than span the entire box, we decided to pad the story titles to the left to better match what was going on with others.

A current view for an automatic issue with a featured image assigned and with featured images attached to a few articles:

![screen shot 2015-11-19 at 1 08 02 pm](https://cloud.githubusercontent.com/assets/286171/11284446/a4d5ba78-8ebe-11e5-853f-db9ce2fe7db1.png)
